swagger: '2.0'
info:
  title: "Library API"
  description: "API to manage library system"
  version: "1.0.0"
host: "127.0.0.1.500"
schemes: 
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /members/login:
    post:
      tags:
        - members
      summary: "Login endpoint, (generates token)"
      description: "Validates member credentials , generates and return a member specific token."
      parameters:
        - in: "body"
          name: "body"
          description: "Login Credentials"
          required: true
          schema:
            $ref: "#definitions/LoginCredentials"
      responses:
        200:
          description: "Login successful"
          schema:
            $ref: "#/definitions/LoginResponse"
definitions:

  LoginCredentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"

      required:
        - email
        - password

  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
      status:
        type: "string"

